### PR TITLE
Add socketio query configuration

### PR DESCRIPTION
**Pull request by n3ps**
To add support for passing in query (handshake) information to a socketio-based test

### CODE REVIEW

**Comment by n3ps** [comment]
Usage will be similar to adding transport configuration:

```
config:
  socketio:
    query: "param=value"
```

**Comment by hassy** [comment]
Nice, thanks @n3ps!

**Comment by BerendWeij** [comment]
@n3ps can you check this issue: https://github.com/shoreditch-ops/artillery-core/issues/165

You are adding the query object to the options in the method loadContextSocket but not in the compile method. I guess both methods are being triggered which results in two connections with socket.io. This results in two bugs:

- The first connection missing the query object and the second connection includes it

- Two connections (instead of one)

**Comment by n3ps** [comment]
@BerendWeij, @hassy I see the two connections bug and I don't think this commit introduced that as I reproduced it in an older version (artillery@1.5.2, artillery-core@2.4.1).

Re: the compile method not having query in options, I'll update that.

**Comment by MaxOvcharov** [comment]
Hi, I'm using  artillery@1.6.0-6. I want to put my query parameters into Socket.io connection:
```config:
  target: "http://127.0.0.1:8080"
  phases:
    - duration: 28800
      arrivalRate: 50
  variables:
    var: ['1', '2']
  processor: "./functions.js"
  socketio:
    transports: ["websocket"]
    query: "user_id=4f5bc00e-8516-49a9-8507-d475d40d06b5"
```
But after artillery is running my server have no message from artillery. Does this a correct way to using "query" parameter?

**Comment by MaxOvcharov** [comment]
@n3ps Can you help me?

**Comment by hassy** [comment]
@MaxOvcharov Do you have a reproducible test case? `query` isn't known to be broken at the moment. If you do, could you open a new issue [on the main repo](https://github.com/shoreditch-ops/artillery) please.

**Comment by MaxOvcharov** [comment]
@hassy Done https://github.com/shoreditch-ops/artillery-core/issues/195

**Pull request merged**
