### PR TITLE
Adding Think jitter

### PR DESCRIPTION
**Pull request by steveschnepp**
Think jitter is nice to bring some randomness in scripts besides the starting time.

### CODE REVIEW

**Comment by steveschnepp** [comment]
This PR is mostly to open comments, maybe not to merge it directly 😉

**Comment by RobGruhl** [comment]
Very cool idea.

**Comment by hassy** [comment]
@steveschnepp Great idea! Sorry for not replying sooner.

I would personally lean towards making `jitter` an explicit attribute of the `think` command like this:

```javascript
{ "think": 5, "jitter": 2 }
// or:
{ "think": 5, "jitter": "10%" }
```

It would also be nice to be able to set a default jitter value for all `think`s in a script/scenario (like you can set default headers to be sent with every HTTP request). Something like this:

```javascript
{
  "config": {
    "defaults": {
      "thinkJitter": "20%"
    }
  },
  "scenarios": [
    // ...
  ]
}
```

Thoughts?

**Comment by steveschnepp** [comment]
Yeah, the modification of the API is much cleaner.

I just went the quick road in order to have the feature for myself, and to be able to show something working quickly.

**Comment by hassy** [comment]
Continuing this in https://github.com/shoreditch-ops/artillery-core/pull/110

**Pull request closed without merging**
