### PR TITLE
Initial set of changes and bug fix to support capture/match in socket.io emit flows

### PR DESCRIPTION
**Pull request by gboysko**
Hello Hassey:

This commit it not intended to be checked in as I have not finished my refactoring. Just getting basic competency in the code base. 

Feel free to review my approach and changes. I admit I don't know if I've followed all of your conventions consistently.

My plan is to next refactor the `captureOrMatch` function into its own module in `engine_utils` and then apply those changes to `engine_http` and `engine_socketio`. 

The callback handler for each of those entry points seems to be very common and perhaps that should be shared as well. 

Any thoughts you have are appreciated.

Regards,
Glenn

### CODE REVIEW

**Comment by hassy** [comment]
Nice. :) Would be good to have a test for the new functionality.

**Comment by gboysko** [comment]
Yes, I'll do that as well. I'm a bit concerned about the lint warnings. I thought that they had to be 0? Also, I'm seeing some unusual numbers when I run my script. For example, I have a single phase with `duration: 60` and `arrivalCount: 500`. So, I would imagine to see concurrent users (at every 10s snapshot) to be between 0 ... 500. However, I'm seeing up to 3000 at time. Does this make sense?

Do you see anything unusual about my changes? Is it consistent with the rest of your code, specifically the async programming model?

**Comment by gboysko** [comment]
@hassy I am not proposing any more changes. Let me know if you need any other changes from me.

**Comment by hassy** [comment]
This is great @gboysko! 👍  Apologies for taking so long to review and merge.

**Comment by gboysko** [comment]
No problem, Hassy.

I had a question for you: Has anyone reported problems with concurrency
values reported? I'm finding for my socket.io scenario, the value is off by
an order of magitude (10x more than actual).

I was going to investigate, but wasn't sure if anyone else reported it and
whether to look.

**Comment by hassy** [comment]
That does not sound right @gboysko. Do you have a simple test case to try to replicate?

I'd start by running a test and looking at something like `netstat -an | grep $SERVER_IP | wc -l` to see if the number of connections reported by Artillery corresponds to the number of actual open TCP connections. That would point us towards whether the bug is in the code that keeps track of concurrent users or in the code that actually launches them.

**Comment by gboysko** [comment]
Yes, I have a simple test case that runs for about a minute and a half.
Each scenario consists of 6 messages and (with wait time) lasts for 70s.

I have a single phase with a duration of 60 and an arrival count of 50.

The value of `netstat -n | grep $SERVER_IP | wc -l` started at 18 (before
any tests were run) and went up to 28.

The concurrency reported by each snapshot ranged from 0 to 480.

I'm including both the Report and HTML.

Definitely very broken.

**Pull request merged**
